services:
  app:
    image: flask_image
    build: ./flask
    container_name: my_flask_container
    networks:
      - my_network
    volumes:
      - type: bind
        source: ./flask/file.txt
        target: /app/file.txt
        read_only: false

  nginx:
    image: nginx_image
    build: ./nginx
    container_name: nginx_container
    ports:
      - "80:80"
    networks:
      - my_network
    depends_on:
      - app
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true


networks:
  my_network:
    driver: bridge



