from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "bCDNi5NtUSBuTmYgE0vvS6uZ"

# Create the client instance
client = Elasticsearch(
    "https://elastic-latest.netbuilder-training.com",
    #ca_certs="ca.crt",
    #client_cert="tls.crt",
    #client_key="tls.key",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
print(client.info())
# {'name': 'instance-0000000000', 'cluster_name': ...}

